osx_image: xcode10.1
language: objective-c

xcode_project: FoldingCell/FoldingCell.xcodeproj
xcode_scheme: FoldingCell
xcode_sdk: iphonesimulator11.2

SWIFT_VERSION: 4.2

# whitelist
branches:
only:
- master
